GET http://localhost:8000/room

###
GET http://localhost:8000/event/2

###
POST http://localhost:8000/room/add
content-Type: application/json

{
    "availability": "Available",
      "_id": "614039cb367f063ca436fb09",
      "roomNo": "RID0001",
      "type": "Single Economy ",
      "noOfBeds": 0,
      "price": 15000,
      "description": "Test1",


}

###
PUT   http://localhost:8000/room/update/614d7a5763c09b6100f545de
content-Type: application/json

{
     "type":"p6",
    "roomNo":888,
     "noOfBeds":888,
        "price":888,
        "description":"ss",
         "availability":"s1"
}

###
DELETE  http://localhost:8000/customer/delete/614d7a5763c09b6100f545de
